create table "ADMIN1".OSOBA
(
	ID BIGINT default 0 not null primary key,
	IMIE VARCHAR(50),
	NAZWISKO VARCHAR(100) not null,
	DZIECKO BOOLEAN default false not null,
	POKOJ NUMERIC(5),
	POKOJ_ID BIGINT
);

create table "ADMIN1".POKOJ
(
	ID BIGINT not null primary key,
	NUMER NUMERIC(5) default 0,
	VERSION BIGINT default 0 not null
);

ALTER TABLE OSOBA 
ADD FOREIGN KEY (POKOJ_ID) REFERENCES OSOBA(ID);

INSERT INTO ADMIN1.POKOJ (ID, NUMER, VERSION) 
	VALUES (1, 11, DEFAULT);
INSERT INTO ADMIN1.POKOJ (ID, NUMER, VERSION) 
	VALUES (2, 22, DEFAULT);
INSERT INTO ADMIN1.POKOJ (ID, NUMER, VERSION) 
	VALUES (3, 33, DEFAULT);
INSERT INTO ADMIN1.POKOJ (ID, NUMER, VERSION) 
	VALUES (4, 44, DEFAULT);
INSERT INTO ADMIN1.POKOJ (ID, NUMER, VERSION) 
	VALUES (5, 55, DEFAULT);


INSERT INTO ADMIN1.OSOBA (ID, IMIE, NAZWISKO, DZIECKO, POKOJ_ID) 
	VALUES (1, 'ola', 'kedra', DEFAULT, 1);
INSERT INTO ADMIN1.OSOBA (ID, IMIE, NAZWISKO, DZIECKO, POKOJ_ID) 
	VALUES (2, 'witek', 'potempa', DEFAULT, 2);
INSERT INTO ADMIN1.OSOBA (ID, IMIE, NAZWISKO, DZIECKO, POKOJ_ID) 
	VALUES (3, 'lidka', 'gasiorowska', true, default);

